"""
Configuration settings for Predator: Badlands Simulation
"""

# Grid Configuration
GRID_WIDTH = 25
GRID_HEIGHT = 25
WRAPPING_ENABLED = True

# Agent Starting Positions
DEK_START_POS = (2, 2)
THIA_START_POS = (3, 3)
FATHER_START_POS = (20, 20)
BROTHER_START_POS = (19, 20)

# Agent Attributes
PREDATOR_BASE_HEALTH = 150
PREDATOR_BASE_STAMINA = 120
PREDATOR_BASE_HONOR = 0
SYNTHETIC_BASE_HEALTH = 80

# Movement Costs
MOVE_STAMINA_COST = 2
CARRY_STAMINA_MULTIPLIER = 1.5
ROUGH_TERRAIN_MULTIPLIER = 1.3

# Combat Settings
BASE_ATTACK_DAMAGE = 20
CRIT_CHANCE = 0.15
CRIT_MULTIPLIER = 2.0

# Monster Configuration - OPTIMIZED FOR GAMEPLAY
SMALL_MONSTER_COUNT = 8
MEDIUM_MONSTER_COUNT = 5
LARGE_MONSTER_COUNT = 2
ADVERSARY_COUNT = 1

# Monster Stats
SMALL_MONSTER_HEALTH = 25
MEDIUM_MONSTER_HEALTH = 45
LARGE_MONSTER_HEALTH = 75
ADVERSARY_HEALTH = 300

# Honor/Reputation Values
HONOR_SMALL_KILL = 10
HONOR_MEDIUM_KILL = 25
HONOR_LARGE_KILL = 50
HONOR_ADVERSARY_KILL = 150
HONOR_RETREAT_PENALTY = -10
HONOR_DISHONOR_PENALTY = -25

# Clan Thresholds
HONOR_RESPECT_THRESHOLD = 50
HONOR_WARRIOR_THRESHOLD = 100
HONOR_ELDER_THRESHOLD = 200

# Resource Settings
TROPHY_SLOTS = 5
REST_STAMINA_RECOVERY = 20
REST_HEALTH_RECOVERY = 8

# Simulation Settings
MAX_TURNS = 1000
TURN_DELAY = 0.1

# Terrain Types
TERRAIN_EMPTY = 0
TERRAIN_ROUGH = 1
TERRAIN_TRAP = 2
TERRAIN_OBSTACLE = 3

# Cell Contents
CELL_EMPTY = 'empty'
CELL_PREDATOR = 'predator'
CELL_SYNTHETIC = 'synthetic'
CELL_MONSTER = 'monster'
CELL_ADVERSARY = 'adversary'
CELL_OBSTACLE = 'obstacle'
CELL_TRAP = 'trap'

# Visualization Colors (for tkinter)
COLOR_EMPTY = '#8B7355'
COLOR_ROUGH = '#A0826D'
COLOR_OBSTACLE = '#404040'
COLOR_TRAP = '#8B0000'
COLOR_DEK = '#00FF00'
COLOR_PREDATOR = '#FFD700'
COLOR_THIA = '#4169E1'
COLOR_MONSTER = '#FF4500'
COLOR_ADVERSARY = '#8B008B'

# AI Settings
PATHFINDING_MAX_ITERATIONS = 1000
DECISION_INTERVAL = 1
AGGRO_RANGE = 12
FLEE_HEALTH_THRESHOLD = 0.3

# Yautja Code Enforcement
UNWORTHY_PREY_PENALTY = -30
DISHONOR_KILL_PENALTY = -50
TERRITORY_VIOLATION_PENALTY = -20